version: '3'

services:
  service_1:
    build:
      context: ./service_1
    container_name: service_1
    ports:
      - "8001"
    networks:
      - app-network

  service_2:
    build:
      context: ./service_2
    container_name: service_2
    ports:
      - "8002"
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    depends_on:
      - service_1
      - service_2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
